#!/usr/bin/env bash
fmt <<EOF
Hi there!

Thank you for your interest in dateh. I've moved it to its own repo, as it's taking on a life of its own.

Please go to https://github.com/gromgit/dateh and download the new code.

Thank you for your patronage.

- Adrian Ho
EOF
